/**
 * report.js
 *
 *
 * @category  house
 * @package   Hospitality HouseKeeper
 * @author    Will Ireland <wireland@nonprofitsoftwarecorp.org>
 * @copyright 2010-2026 <nonprofitsoftwarecorp.org>
 * @license   GPL and MIT
 * @link      https://github.com/NPSC/HHK
 */

import $ from "jquery";
import { dateRender, dayRender, flagAlertMessage } from "../common/pag.js";

export function initTimePeriod(config, $scope) {
  var $ctx = $scope || $(document);

  $ctx.find("#selCalendar").on("change", function () {
    $ctx.find("#selIntYear").show();
    if ($(this).val() && $(this).val() != "19") {
      $ctx.find("#selIntMonth").hide();
    } else {
      $ctx.find("#selIntMonth").show();
    }
    if ($(this).val() && $(this).val() != "18") {
      $ctx.find(".dates").hide();
    } else {
      $ctx.find(".dates").show();
      $ctx.find("#selIntYear").hide();
    }
  });
  $ctx.find("#selCalendar").trigger("change");

  $ctx.find(".ckdate").datepicker({
    yearRange: config.startYear + ":+02",
    changeMonth: true,
    changeYear: true,
    autoSize: true,
    numberOfMonths: 1,
    dateFormat: "yy-mm-dd",
  });
}

export function initReport(opts) {
  var $container = $("#" + opts.reportName + "Report");

  initTimePeriod(opts, $container);

  $container.find(".includeFields").fieldSets({
    reportName: opts.reportName,
    defaultFields: opts.defaultFields,
  });

  $container.find(".rptFilterForm").on("submit", function (e) {
    var submitter = e.originalEvent && e.originalEvent.submitter;
    if (!submitter || submitter.name !== "btnHere-" + opts.reportName) {
      return; // not the "Run Here" button (e.g. Excel download) - submit natively
    }
    e.preventDefault();

    $.ajax({
      url: "ws_reportFilter.php",
      type: "POST",
      dataType: "json",
      data: $(this)
        .serializeArray()
        .concat([
          { name: "cmd", value: "runReport" },
          { name: "reportClass", value: opts.reportClass },
        ]),
      success: function (response) {
        if (response.error) {
          flagAlertMessage(response.error, true);
          return;
        }
        $container.find(".rptResults").html(response.markup);
        initReportTable($container, response.config, opts.dateFormat, opts.drawCallback);
      },
      error: function () {
        flagAlertMessage("An unknown error occurred", true);
      },
    });
  });

  if (opts.rendered) {
    initReportTable($container, opts, opts.dateFormat, opts.drawCallback);
  }
}

function initReportTable($container, config, dateFormat, drawCallback) {
  var $table = $container.find(".rptTable");
  var $emailDialog = $container.find(".emRptDialog");

  var dtOptions = {
    columnDefs: [
      {
        targets: config.columnDefs,
        type: "date",
        render: (data, type) => dateRender(data, type, dateFormat),
      },
      {
        targets: config.dateTimeColumnDefs,
        type: "date",
        render: (data, type) => dateRender(data, type, dateFormat + " h:mm a"),
      },
      {
        targets: config.dayColumnDefs,
        type: "date",
        render: (data, type) => dayRender(data, type, "MMM Do"),
      },
    ],
    displayLength: 50,
    lengthMenu: [
      [25, 50, 100, -1],
      [25, 50, 100, "All"],
    ],
    order: [[config.defaultSortCol, "asc"]],
    layout: {
      top1Start: {
        buttons: [
          {
            extend: "print",
            className: "ui-corner-all",
            autoPrint: true,
            paperSize: "letter",
            title: () => config.reportTitle,
            messageTop: () => $container.find("#repSummary").prop("outerHTML"),
            messageBottom: () => {
              var now = moment().format(config.dateTimeFormat);
              return (
                '<div style="padding-top: 10px; position: fixed; bottom: 0; right: 0">Generated by <strong>' +
                config.username +
                "</strong> on " +
                now +
                "</div>"
              );
            },
            customize: (win) => {
              $(win.document.body).css("font-size", "0.9em");
              $(win.document.body).find("table").css("font-size", "inherit");
            },
          },
          {
            text: "Email",
            className: "ui-corner-all",
            action: () => {
              $emailDialog.dialog("open");
            },
          },
        ],
      },
    },
  };

  if (typeof drawCallback === "function") {
    dtOptions.drawCallback = drawCallback;
  }

  $table.dataTable(dtOptions);

  $emailDialog.dialog({
    autoOpen: false,
    modal: true,
    title: "Email " + config.reportTitleDecoded,
    width: "auto",
    buttons: {
      Send: function () {
        var data = $container.find(".rptFilterForm").serializeArray();
        data.push({ name: "btn" + config.reportName + "Email", value: "true" });
        data.push({ name: "txtSubject", value: $(this).find("#txtSubject").val() });
        data.push({ name: "txtEmail", value: $(this).find("#txtEmail").val() });
        $.ajax({
          type: "post",
          data: data,
          dataType: "json",
          success: function (data) {
            if (data.success) {
              flagAlertMessage(data.success, false);
              $emailDialog.dialog("close");
            } else if (data.error) {
              flagAlertMessage(data.error, true);
            } else {
              flagAlertMessage("An unknown error occurred", true);
            }
          },
        });
      },
    },
  });
}
